### ISSUE TITLE
 The Baiduversion of the dataset

### ISSUE THREAD

**Issue by Jasper0068** [HengLan/PlanarTrack#1]
Thank you for your outstanding work!
Due to the instability of the domestic network(VPN), is it possible to provide the dataset in Baidu  Cloud Drive format.
Good luck!

**Comment by HengLan** [comment]
Hi,

Thanks for your interest. Since there is a difficulty for us in hosting such as a large file in BauduYun, we choose to release it on OneDrive. However, we will consider to release it on BaiduYun if the problem is solved.
